# Form implementation generated from reading ui file 'quiz3.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(286, 300)
        Dialog.setModal(False)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 261, 41))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../bog_eng_vertical.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.radioButton = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton.setGeometry(QtCore.QRect(10, 60, 81, 21))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(110, 60, 51, 21))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=Dialog)
        self.radioButton_3.setGeometry(QtCore.QRect(200, 60, 51, 21))
        self.radioButton_3.setObjectName("radioButton_3")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 71, 16))
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(parent=Dialog)
        self.textEdit.setGeometry(QtCore.QRect(10, 110, 221, 21))
        self.textEdit.setObjectName("textEdit")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 51, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(110, 140, 61, 16))
        self.label_4.setObjectName("label_4")
        self.dateEdit = QtWidgets.QDateEdit(parent=Dialog)
        self.dateEdit.setGeometry(QtCore.QRect(10, 160, 61, 21))
        self.dateEdit.setObjectName("dateEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(110, 160, 41, 21))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 200, 81, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(10, 220, 91, 16))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setGeometry(QtCore.QRect(100, 260, 71, 21))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.radioButton.setText(_translate("Dialog", " Mastercard"))
        self.radioButton_2.setText(_translate("Dialog", "Visa"))
        self.radioButton_3.setText(_translate("Dialog", " AMEX"))
        self.label_2.setText(_translate("Dialog", "Card number"))
        self.label_3.setText(_translate("Dialog", "Date"))
        self.label_4.setText(_translate("Dialog", "CVC"))
        self.label_5.setText(_translate("Dialog", "one-time code"))
        self.pushButton.setText(_translate("Dialog", "Pay"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())

